# =============================================================================
# LoyalCorp P1 Bot — SIP Trunk Manager (Admin)
# =============================================================================
# Admin can set SIP trunk credentials via bot.
# Bot writes pjsip_loyalcorp.conf and reloads Asterisk.
# =============================================================================

import os
import subprocess
import logging
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ContextTypes

logger = logging.getLogger(__name__)

PJSIP_CONF_PATH     = "/etc/asterisk/pjsip_loyalcorp.conf"
ASTERISK_RELOAD_CMD = 'asterisk -rx "pjsip reload"'


def _generate_conf(host: str, username: str, password: str) -> str:
    return (
        f"; Auto-generated by LoyalCorp P1 Bot\n"
        f"; =============================================================================\n\n"
        f"[loyalcorp-transport]\n"
        f"type=transport\n"
        f"protocol=udp\n"
        f"bind=0.0.0.0:5060\n\n"
        f"[loyalcorp-registration]\n"
        f"type=registration\n"
        f"transport=loyalcorp-transport\n"
        f"outbound_auth=loyalcorp-auth\n"
        f"server_uri=sip:{host}\n"
        f"client_uri=sip:{username}@{host}\n"
        f"retry_interval=60\n"
        f"max_retries=10\n"
        f"contact_user={username}\n\n"
        f"[loyalcorp-auth]\n"
        f"type=auth\n"
        f"auth_type=userpass\n"
        f"username={username}\n"
        f"password={password}\n\n"
        f"[loyalcorp-aor]\n"
        f"type=aor\n"
        f"contact=sip:{host}\n"
        f"qualify_frequency=60\n\n"
        f"[loyalcorp_trunk]\n"
        f"type=endpoint\n"
        f"transport=loyalcorp-transport\n"
        f"context=loyalcorp-p1-ivr\n"
        f"disallow=all\n"
        f"allow=ulaw\n"
        f"allow=alaw\n"
        f"outbound_auth=loyalcorp-auth\n"
        f"outbound_proxy=sip:{host}\\;lr\n"
        f"from_user={username}\n"
        f"from_domain={host}\n"
        f"aors=loyalcorp-aor\n"
        f"direct_media=no\n"
        f"trust_id_inbound=yes\n"
        f"send_pai=yes\n"
        f"callerid_privacy=allowed_not_screened\n"
    )


def _read_current_trunk() -> dict:
    """Read current trunk info from pjsip config."""
    info = {"host": "Not configured", "username": "Not configured"}
    if not os.path.exists(PJSIP_CONF_PATH):
        return info
    try:
        with open(PJSIP_CONF_PATH, "r") as f:
            for line in f:
                line = line.strip()
                if line.startswith("server_uri=sip:"):
                    info["host"] = line.replace("server_uri=sip:", "").strip()
                elif line.startswith("username="):
                    info["username"] = line.replace("username=", "").strip()
    except Exception:
        pass
    return info


async def show_trunk_menu(query, context):
    """Show current trunk info and options."""
    info = _read_current_trunk()
    text = (
        f"🔌 <b>SIP Trunk Configuration</b>\n\n"
        f"Host: <code>{info['host']}</code>\n"
        f"Username: <code>{info['username']}</code>\n\n"
        f"<b>To update trunk credentials:</b>\n"
        f"Send in this format:\n"
        f"<code>host username password</code>\n\n"
        f"Example:\n"
        f"<code>sip.callerpro.com myuser mypass123</code>"
    )
    context.user_data["admin_trunk_step"] = "waiting_input"
    await query.edit_message_text(
        text, parse_mode="HTML",
        reply_markup=InlineKeyboardMarkup([
            [InlineKeyboardButton("🔄 Reload Asterisk", callback_data="admin_trunk_reload")],
            [InlineKeyboardButton("🔙 Admin Panel",    callback_data="admin_panel")]
        ])
    )


async def handle_trunk_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handle admin_trunk and admin_trunk_reload callbacks."""
    query = update.callback_query
    await query.answer()
    data = query.data

    if data == "admin_trunk":
        await show_trunk_menu(query, context)

    elif data == "admin_trunk_reload":
        try:
            result = subprocess.run(
                ASTERISK_RELOAD_CMD, shell=True,
                capture_output=True, text=True, timeout=15
            )
            out = (result.stdout + result.stderr).strip()[:300] or "No output"
            await query.edit_message_text(
                f"✅ <b>Asterisk PJSIP Reloaded</b>\n\n<code>{out}</code>",
                parse_mode="HTML",
                reply_markup=InlineKeyboardMarkup([
                    [InlineKeyboardButton("🔌 Trunk", callback_data="admin_trunk")],
                    [InlineKeyboardButton("🔙 Admin", callback_data="admin_panel")]
                ])
            )
        except Exception as e:
            await query.edit_message_text(
                f"❌ Reload failed: <code>{str(e)[:200]}</code>",
                parse_mode="HTML",
                reply_markup=InlineKeyboardMarkup([
                    [InlineKeyboardButton("🔙 Admin", callback_data="admin_panel")]
                ])
            )


async def handle_trunk_input(update: Update, context: ContextTypes.DEFAULT_TYPE) -> bool:
    """
    Called from handle_message when admin_trunk_step == 'waiting_input'.
    Returns True if handled, False otherwise.
    """
    if context.user_data.get("admin_trunk_step") != "waiting_input":
        return False

    text = (update.message.text or "").strip()
    parts = text.split()

    if len(parts) < 3:
        await update.message.reply_text(
            "❌ Invalid format. Send:\n<code>host username password</code>",
            parse_mode="HTML"
        )
        return True

    host, username, password = parts[0], parts[1], parts[2]
    conf_content = _generate_conf(host, username, password)

    try:
        with open(PJSIP_CONF_PATH, "w") as f:
            f.write(conf_content)
        context.user_data.pop("admin_trunk_step", None)

        # Auto-reload Asterisk
        result = subprocess.run(
            ASTERISK_RELOAD_CMD, shell=True,
            capture_output=True, text=True, timeout=15
        )
        out = (result.stdout + result.stderr).strip()[:200] or "OK"

        await update.message.reply_text(
            f"✅ <b>Trunk Updated & Reloaded!</b>\n\n"
            f"Host: <code>{host}</code>\n"
            f"User: <code>{username}</code>\n"
            f"Pass: <code>{'*' * len(password)}</code>\n\n"
            f"Asterisk output:\n<code>{out}</code>",
            parse_mode="HTML",
            reply_markup=InlineKeyboardMarkup([
                [InlineKeyboardButton("🔌 Trunk Menu", callback_data="admin_trunk")],
                [InlineKeyboardButton("🔙 Admin",      callback_data="admin_panel")]
            ])
        )
    except PermissionError:
        await update.message.reply_text(
            f"❌ <b>Permission denied!</b>\n\n"
            f"Cannot write to <code>{PJSIP_CONF_PATH}</code>\n"
            f"Run the bot as root or grant write permission.",
            parse_mode="HTML"
        )
    except Exception as e:
        await update.message.reply_text(f"❌ Error: {str(e)[:200]}")

    return True